-- Migration 019: Idempotent finalize per harmonizationKey (B2, ruling C).
--
-- HOUSE DOCTRINE (first DML-on-RLS migration): m1.documents has FORCE ROW
-- LEVEL SECURITY. The migrator runs as a superuser/master role, but RLS
-- FORCE mode applies policies even to table owners. We bracket the DML with
-- NO FORCE → FORCE to allow cross-tenant backfill operations.
--
-- NOTE: no BEGIN/COMMIT — the migration runner owns the transaction.
--
-- Problem: two generation runs for the same tenant produce duplicate clause
-- documents (dev: 101 docs, 48 doubled titles). Root cause: insertDocument
-- does a bare INSERT with no conflict handling.
--
-- Fix: add harmonization_key to m1.documents, derive from generation lineage,
-- dedup, THEN create the partial unique index (keys → dedup → index order
-- avoids 23505 on pre-existing duplicates).

-- ═══════════════════════════════════════════════════════════════════════════════
-- SCHEMA: add column (index created AFTER dedup — step order matters)
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE m1.documents ADD COLUMN IF NOT EXISTS harmonization_key TEXT NULL;

-- ═══════════════════════════════════════════════════════════════════════════════
-- BACKFILL: derive harmonization_key, then dedup.
-- RLS bypass bracket (house doctrine for DML-on-RLS migrations).
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE m1.documents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE m1.document_versions NO FORCE ROW LEVEL SECURITY;

-- Step 1: Derive harmonization_key from generation lineage for finalize-produced docs.
-- clauseDocTitle() embeds sectionKey in the title as "(sectionKey)" at the end.
-- Well-known singletons get fixed keys.
-- policy/scope docs are NOT finalize-produced (they come from createDocumentDraft
-- / agentDraftDocument) — their titles don't carry "(sectionKey)", so the regex
-- returns NULL and they stay exempt from the partial unique index. The 92
-- policy/scope rows are DEFERRED (see evidence log: separate dedup mechanism,
-- cosmetic-only cost).
UPDATE m1.documents
SET harmonization_key = CASE
  WHEN doc_type = 'manual' THEN '__MANUAL__'
  WHEN doc_type = 'correlation_matrix' THEN '__CORRELATION_MATRIX__'
  WHEN doc_type = 'master_list' THEN '__MASTER_LIST__'
  ELSE substring(title FROM '\(([^)]+)\)$')
END
WHERE doc_type IN ('manual', 'procedure', 'work_instruction', 'correlation_matrix', 'master_list')
  AND harmonization_key IS NULL;

-- Step 2: Version disposition for FK-referenced duplicates.
-- For each (tenant_id, harmonization_key) group with >1 row, keep the LATEST
-- (highest updated_at). Versions on duplicates are disposed per rule:
-- human-edited → re-parent to survivor; pure-machine v1 → delete.

-- 2a: Re-parent human-edited versions (version_no > 1 or non-standard summary)
-- from duplicates to their survivor document.
WITH survivors AS (
  SELECT DISTINCT ON (tenant_id, harmonization_key)
    id, tenant_id, harmonization_key
  FROM m1.documents
  WHERE harmonization_key IS NOT NULL
  ORDER BY tenant_id, harmonization_key, updated_at DESC
),
duplicates AS (
  SELECT d.id AS dup_id, s.id AS survivor_id
  FROM m1.documents d
  JOIN survivors s ON s.tenant_id = d.tenant_id
    AND s.harmonization_key = d.harmonization_key
    AND s.id != d.id
  WHERE d.harmonization_key IS NOT NULL
)
UPDATE m1.document_versions v
SET document_id = dup.survivor_id
FROM duplicates dup
WHERE v.document_id = dup.dup_id
  AND (v.version_no > 1 OR v.change_summary IS DISTINCT FROM 'Generated by DocGen run');

-- 2b: Delete pure-machine versions (v1, standard summary) on duplicates.
WITH survivors AS (
  SELECT DISTINCT ON (tenant_id, harmonization_key)
    id, tenant_id, harmonization_key
  FROM m1.documents
  WHERE harmonization_key IS NOT NULL
  ORDER BY tenant_id, harmonization_key, updated_at DESC
),
duplicates AS (
  SELECT d.id AS dup_id
  FROM m1.documents d
  JOIN survivors s ON s.tenant_id = d.tenant_id
    AND s.harmonization_key = d.harmonization_key
    AND s.id != d.id
  WHERE d.harmonization_key IS NOT NULL
)
DELETE FROM m1.document_versions
WHERE document_id IN (SELECT dup_id FROM duplicates);

-- 2c: Delete duplicate document rows (zero FK references remain).
WITH survivors AS (
  SELECT DISTINCT ON (tenant_id, harmonization_key)
    id, tenant_id, harmonization_key
  FROM m1.documents
  WHERE harmonization_key IS NOT NULL
  ORDER BY tenant_id, harmonization_key, updated_at DESC
)
DELETE FROM m1.documents
WHERE harmonization_key IS NOT NULL
  AND id NOT IN (SELECT id FROM survivors);

-- Re-enable RLS enforcement.
ALTER TABLE m1.documents FORCE ROW LEVEL SECURITY;
ALTER TABLE m1.document_versions FORCE ROW LEVEL SECURITY;

-- ═══════════════════════════════════════════════════════════════════════════════
-- INDEX: created AFTER dedup (avoids 23505 on pre-existing duplicate keys).
-- Partial unique: one generated document per tenant per harmonization_key.
-- NULL harmonization_key (manually created / policy / scope docs) is exempt.
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE UNIQUE INDEX IF NOT EXISTS idx_m1_documents_tenant_hk
  ON m1.documents (tenant_id, harmonization_key)
  WHERE harmonization_key IS NOT NULL;
