-- Migration 019: Idempotent finalize per harmonizationKey (B2, ruling C).
--
-- HOUSE DOCTRINE (first DML-on-RLS migration): m1.documents has FORCE ROW
-- LEVEL SECURITY. The migrator runs as a superuser/master role, but RLS
-- FORCE mode applies policies even to table owners. We bracket the DML with
-- NO FORCE → FORCE to allow cross-tenant backfill operations.
--
-- Problem: two generation runs for the same tenant produce duplicate clause
-- documents (dev: 101 docs, 48 doubled titles). Root cause: insertDocument
-- does a bare INSERT with no conflict handling.
--
-- Fix: add harmonization_key to m1.documents + partial unique index so
-- ON CONFLICT DO UPDATE makes finalize idempotent per section identity.

BEGIN;

-- ═══════════════════════════════════════════════════════════════════════════════
-- SCHEMA: add column + partial unique index
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE m1.documents ADD COLUMN IF NOT EXISTS harmonization_key TEXT NULL;

-- Partial unique: one generated document per tenant per harmonization_key.
-- NULL harmonization_key (manually created docs) is exempt (partial index).
CREATE UNIQUE INDEX IF NOT EXISTS idx_m1_documents_tenant_hk
  ON m1.documents (tenant_id, harmonization_key)
  WHERE harmonization_key IS NOT NULL;

-- ═══════════════════════════════════════════════════════════════════════════════
-- BACKFILL: derive harmonization_key from generation lineage, dedup safely.
-- RLS bypass bracket (house doctrine for DML-on-RLS migrations).
-- ═══════════════════════════════════════════════════════════════════════════════

ALTER TABLE m1.documents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE m1.document_versions NO FORCE ROW LEVEL SECURITY;

-- Step 1: Derive harmonization_key from title for ALL finalize-produced docs.
-- clauseDocTitle() embeds sectionKey in the title as "(sectionKey)" at the end.
-- Well-known singletons get fixed keys.
UPDATE m1.documents
SET harmonization_key = CASE
  WHEN doc_type = 'manual' THEN '__MANUAL__'
  WHEN doc_type = 'correlation_matrix' THEN '__CORRELATION_MATRIX__'
  WHEN doc_type = 'master_list' THEN '__MASTER_LIST__'
  ELSE substring(title FROM '\(([^)]+)\)$')
END
WHERE doc_type IN ('manual', 'procedure', 'work_instruction', 'correlation_matrix', 'master_list')
  AND harmonization_key IS NULL;

-- Step 2: Identify duplicates. For each (tenant_id, harmonization_key) group
-- with >1 row, keep the LATEST (highest updated_at); mark others for removal.
-- Version disposition: re-parent or delete orphaned versions.
--
-- Safety check: if ANY version on a duplicate has version_no > 1 or
-- change_summary != 'Generated by DocGen run', it was human-edited →
-- re-parent to survivor. Otherwise (pure machine v1) → delete.

-- 2a: Re-parent human-edited versions (version_no > 1 or non-standard summary)
-- from duplicates to their survivor document.
WITH survivors AS (
  SELECT DISTINCT ON (tenant_id, harmonization_key)
    id, tenant_id, harmonization_key
  FROM m1.documents
  WHERE harmonization_key IS NOT NULL
  ORDER BY tenant_id, harmonization_key, updated_at DESC
),
duplicates AS (
  SELECT d.id AS dup_id, s.id AS survivor_id
  FROM m1.documents d
  JOIN survivors s ON s.tenant_id = d.tenant_id
    AND s.harmonization_key = d.harmonization_key
    AND s.id != d.id
  WHERE d.harmonization_key IS NOT NULL
)
UPDATE m1.document_versions v
SET document_id = dup.survivor_id
FROM duplicates dup
WHERE v.document_id = dup.dup_id
  AND (v.version_no > 1 OR v.change_summary IS DISTINCT FROM 'Generated by DocGen run');

-- 2b: Delete pure-machine versions (v1, standard summary) on duplicates.
WITH survivors AS (
  SELECT DISTINCT ON (tenant_id, harmonization_key)
    id, tenant_id, harmonization_key
  FROM m1.documents
  WHERE harmonization_key IS NOT NULL
  ORDER BY tenant_id, harmonization_key, updated_at DESC
),
duplicates AS (
  SELECT d.id AS dup_id
  FROM m1.documents d
  JOIN survivors s ON s.tenant_id = d.tenant_id
    AND s.harmonization_key = d.harmonization_key
    AND s.id != d.id
  WHERE d.harmonization_key IS NOT NULL
)
DELETE FROM m1.document_versions
WHERE document_id IN (SELECT dup_id FROM duplicates);

-- 2c: Now safe to delete duplicate document rows (no FK references remain).
WITH survivors AS (
  SELECT DISTINCT ON (tenant_id, harmonization_key)
    id, tenant_id, harmonization_key
  FROM m1.documents
  WHERE harmonization_key IS NOT NULL
  ORDER BY tenant_id, harmonization_key, updated_at DESC
)
DELETE FROM m1.documents
WHERE harmonization_key IS NOT NULL
  AND id NOT IN (SELECT id FROM survivors);

-- Re-enable RLS enforcement.
ALTER TABLE m1.documents FORCE ROW LEVEL SECURITY;
ALTER TABLE m1.document_versions FORCE ROW LEVEL SECURITY;

COMMIT;
